name: Build on specific PHP & Laravel versions
on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            php: [8.1, 8.2]
            laravel: [ '^9', '^10' ]
    steps:
      -   uses: actions/checkout@v2
          if: success()

      -   name: Setup PHP with coverage driver
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            coverage: pcov

      -   name: Set Minimum PHP 8.1 Versions
          uses: nick-fields/retry@v2
          with:
            timeout_minutes: 5
            max_attempts: 5
            command: composer require symfony/css-selector:^6.0 --no-interaction --no-update

      -   name: Set Minimum PHP 8.2 Versions
          uses: nick-fields/retry@v2
          with:
              timeout_minutes: 5
              max_attempts: 5
              command: composer require guzzlehttp/guzzle:^7.5 guzzlehttp/psr7:^2.4 predis/predis:^2.0.2 --no-interaction --no-update
          if: matrix.php >= 8.2

      - name: Set Laravel Version
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require laravel/framework:${{ matrix.laravel }} --no-interaction --no-update

      - name: Set Testbench Version for Laravel ^9
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require orchestra/testbench:^7 --dev --no-interaction --no-update
        if: matrix.laravel == '^9'

      - name: Set Testbench Version for Laravel ^10
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require orchestra/testbench:^8 --dev --no-interaction --no-update
        if: matrix.laravel == '^10'

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      -   name: Setup
          if: success()
          run: |
            php -v
            touch coverage.xml
            mv .env.mysql .env
            sudo service mysql start
            mysql -uroot -proot -e "CREATE DATABASE eloquentdocs;"

      -   name: PHPUnit tests
          if: success()
          run: |
            composer test