name: Build on specific PHP & Laravel versions
on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            php: [8.2, 8.3]
            laravel: [ '^11' ]
    steps:
      -   uses: actions/checkout@v3
          if: success()

      -   name: Setup PHP with coverage driver
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            coverage: pcov

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      -   name: Setup
          if: success()
          run: |
            php -v
            touch coverage.xml
            mv .env.mysql .env
            sudo service mysql start
            mysql -uroot -proot -e "CREATE DATABASE eloquentdocs;"

      -   name: PHPUnit tests
          if: success()
          run: |
            composer test